version: 2.1

workflows:
  build_test_deploy:
    jobs:
      - build 
      - unit_tests:
          requires:
            - build  
      - snapshot_tests:
          requires:
            - build
      - build_docker_deploy:
          requires:
            - unit_tests
            - snapshot_tests

######################################################################################
######################################## Jobs ########################################
######################################################################################

jobs:
  build:
    executor: node
    steps:
        - checkout
        - node/install-packages:
            pkg-manager: yarn
  unit_tests:
    docker:
      - image: cimg/node:14.0.0
    parallelism: 10
    steps:
      - checkout
      - run:
          name: Test application 
          command: |
            TEST=$(circleci tests glob **/src/**/*.test.js | circleci tests split --split-by=timings)
            npm test $TEST
      - store_test_results:
          path: ~/project/test-results
      - store_artifacts:
          path: ~/project/test-results/junit.xml
  snapshot_tests:
    docker:
      - image: cimg/node:14.0.0
    steps:
      - checkout
      - run:
          name: Snapshot Tests 
          command: |
            npm run snapshots
  build_docker_deploy:
    docker:
      - image: cimg/node:14.0.0
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: 
          name: Build Docker image
          # basic commands executed via the shell
          command: |
            docker build -t tannerwride/guidedtour -t tannerwride/guidedtour:0.0.1 .
            
                      



#######################################################################################
################################## 2.1 Config Pieces ##################################
#######################################################################################
orbs:
  node: circleci/node@3.0.1
  docker: circleci/docker@2.1.2  
executors:
  node:
    docker: 
      - image: cimg/node:14.0.0
  base:
    docker:
      - image: cimg/base:stable
